# Site settings
title: Penang
client:
  name: Qatar Airways
  link: https://www.qatarairways.com/en-gb/homepage.html?cid=BAGB666480
core-se-link: https://www.secretescapes.com/current-sales
description: >
  A thrilling fusion of Southeast Asian cultures, Penang is the sparkling gem of Malaysia’s northwest coast. From the bustling night markets, breathtaking temples, traditional shophouses and foodie delights of Georgetown, to the sprawling rainforests and aquatic wonders of the island’s natural habitats - fly with Qatar Airways to the ‘Pearl of the Orient’, where a menagerie of hidden treasures are just waiting to be found...

# file paths
url:     "https://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/penang" # the subpath of your site, e.g. /blog/
img:     "/penang/_assets/img"
css:     "/penang/_assets/css"
js:      "/penang/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed